### PR TITLE
QPT-7558 Add webpack and redux dependencies for quill3

### PR DESCRIPTION
**Pull request by ns-ctruong**
@msmathers @jonpo @Salt7900 @ns-gbernsleone 

* Add post-css loader to include autoprefixer in quill 3 webpack
* Add redux mock store for unit testing

### CODE REVIEW

**Comment by ns-ctruong** [comment]
@ns-gbernsleone I added a commit to include a package from our private npm repo.  Just used nixfromnpm for that, but could you double check the output?  It looks like it creates a folder for `@narrativescience` and will put the private package there.

**Comment by ns-gbernsleone** [comment]
@adnelson thoughts on this? Rationale for using NPM for this is that we want to share with Viz.

**Comment by adnelson** [comment]
No, we shouldn't put a private package in a public repo. The definitions of NS node packages should go in the `quill` repo.

**Review by ns-gbernsleone — APPROVED** [review]
LGTM

**Pull request merged**
